### ISSUE TITLE
--style dicom is not listed as an option

### ISSUE THREAD

**Issue by yarikoptic** [Open-Minds-Lab/mrQA#21]
* mrQA version: 

"impossible" to figure out -- please add `--version`:

```
bids@rolando:/inbox/BIDS/Wager/Wager/1076_spacetop$ ~/.local/bin/mr_proto_compl --version
usage: mr_proto_compl -d DATA_ROOT [-o OUTPUT_DIR] [-s STYLE] [-n NAME] [-h] [-r] [-v] [-ref REFERENCE_PATH] [--strategy STRATEGY] [--include_phantom] [--metadata_root METADATA_ROOT] [-l LOGGING] [--skip SKIP [SKIP ...]]
mr_proto_compl: error: the following arguments are required: -d/--data_root
```

* Operating System: singularity reproin container 

```
bids@rolando:/inbox/BIDS/Wager/Wager/1076_spacetop$ ~/.local/bin/mr_proto_compl --help | grep -A1 -e '-s STYLE,'
  -s STYLE, --style STYLE
                        type of dataset, one of [xnat|bids|other]
```

So - no `dicom` is given as an option at all. 

<details>
<summary>Moreover that intriguing `other` I am not sure what it is about</summary> 

```shell
bids@rolando:/inbox/BIDS/Wager/Wager/1076_spacetop$ ~/.local/bin/mr_proto_compl --data_root ./sourcedata/sub-0001/ses-01/ --output_dir .heudiconv/mrQA --style other
/home/bids/singularity_home/.local/lib/python3.9/site-packages/mrQA/cli.py:84: UserWarning: Expected a unique identifier for caching data. Got NoneType. Using a random name. Use --name flag for persistent metadata
  dataset = import_dataset(data_root=args.data_root,
Traceback (most recent call last):
  File "/home/bids/singularity_home/.local/bin/mr_proto_compl", line 8, in <module>
    sys.exit(main())
  File "/home/bids/singularity_home/.local/lib/python3.9/site-packages/mrQA/cli.py", line 84, in main
    dataset = import_dataset(data_root=args.data_root,
  File "/home/bids/singularity_home/.local/lib/python3.9/site-packages/MRdataset/base.py", line 81, in import_dataset
    dataset_class = find_dataset_using_style(style.lower())
  File "/home/bids/singularity_home/.local/lib/python3.9/site-packages/MRdataset/base.py", line 113, in find_dataset_using_style
    dataset_lib = importlib.import_module(dataset_modulename)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'MRdataset.other_dataset'
```
</details>

**Comment by raamana** [comment]
thanks yarik for this great testing and detailed reports. We will look into and fix this asap. Sorry to get you to run into basis issues - we will up our testing to the best of our abilities.

**Comment by sinhaharsh** [comment]
The issue has been fixed. Although the option is called --format now.
