### ISSUE TITLE
No DICOMs found

### ISSUE THREAD

**Issue by araikes** [Open-Minds-Lab/mrQA#54]
* mrQA version: pip current version
* Python version: 3.10
* Operating System: Centos 7

### Description

Siemens enhanced DICOMs without dcm extension doesn't find DICOMS

### What I Did

```
(qctools) [adamraikes@gpu68 allo_phase2]$ mrqa --data-source $PWD/dicoms/000052/Screening/666e4ef2/ --format dicom --name test     
Traceback (most recent call last):
  File "/home/u26/adamraikes/.conda/envs/qctools/bin/mrqa", line 8, in <module>
    sys.exit(main())
  File "/home/u26/adamraikes/.conda/envs/qctools/lib/python3.10/site-packages/mrQA/cli.py", line 85, in main
    check_compliance(dataset=dataset,
  File "/home/u26/adamraikes/.conda/envs/qctools/lib/python3.10/site-packages/mrQA/project.py", line 63, in check_compliance
    raise DatasetEmptyException
MRdataset.config.DatasetEmptyException: Expected Sidecar DICOM/JSON files in --data_source. Got 0 DICOM/JSON files.

```

**Comment by sinhaharsh** [comment]
@araikes This should not happen if the folder contains dicom files. `mrqa` doesn't check for extension to filter dicom files. 

It skips localizer/phantom/head scouts in the folder. The function used for selecting dicom files can be seen [here](https://github.com/Open-Minds-Lab/MRdataset/blob/ce569fd8f37a7ca1fe11f5b8debb609bca45e25d/MRdataset/dicom_utils.py#L80)

**Comment by raamana** [comment]
Harsh, it might also be due to them being Enhanced DICOM format. We need to start testing MRdataset and mrQA on that format. Let’s try to find a dataset in that format.

**Comment by sinhaharsh** [comment]
@araikes Would it be possible to share just a single slice of the Enhanced DICOM format? So that we can debug this issue?

**Comment by raamana** [comment]
Regardless of the format, the output error message was inaccurate - we should improve it to be more direct, and issue an warning for each folder ignored / not included
